### ISSUE TITLE
Google  Login Is not working !

### ISSUE THREAD

**Issue by VibhuGautam** [Ekamba/Souvenirs#1]
The Google Sign  In is not working. It is giving authorization error

**Comment by Ekamba** [comment]
Thanks for your feedback @VibhuGautam , the problem should be possible I have forgotten to update the hosting url in my Google settings account. I will do it and let you know 🙂.

**Comment by Ekamba** [comment]
I have fixed the issue you can check it out 🎉

**Comment by VibhuGautam** [comment]
Hello...
Can you tell me what changes did you made in the developer console ?
What extra urls did you add ?

**Comment by VibhuGautam** [comment]
I also fixed the issue.... I just added the host name onto the
Authorization url

**Comment by Ekamba** [comment]
Hi again, yes exactly I have added the host URL in the Authorization field from google setting in my app.
